### ISSUE TITLE
ツイートの途中に表示される「おすすめユーザー」を非表示にするオプションの追加

### ISSUE THREAD

**Issue by noraworld** [yusukesaitoh/calm-twitter#10]
ツイートの途中に表示される「おすすめユーザー」を非表示にするオプションも追加していただけるとありがたいです。

<img width="598" src="https://user-images.githubusercontent.com/17060801/90333813-d0279480-e003-11ea-832f-c7cec9974907.png">

**Comment by yusukesaitoh** [comment]
バージョン1.1.0にてオプションを追加、Chromeウェブストア配布版にも反映されています。
https://github.com/yusukesaitoh/calm-twitter/releases/tag/1.1.0

**Comment by noraworld** [comment]
ご対応ありがとうございました :pray:
