### ISSUE TITLE
"More Tweets" 削除オプション

### ISSUE THREAD

**Issue by noraworld** [yusukesaitoh/calm-twitter#22]
ツイートの詳細ページの下に出てくる "More Tweets" を削除するオプションをつけていただけるとありがたいです。

<img width="591" alt="Screen Shot 2022-03-19 at 15 30 41" src="https://user-images.githubusercontent.com/17060801/159110329-41b2f473-e553-40f9-90c9-5620f68d749a.png">

**Comment by yusukesaitoh** [comment]
リクエストありがとうございます。
現在この拡張機能はCSSで指定できる要素のみ隠せる実装になっているのですが、More Tweetsのみを指定するセレクタがなく、今の仕組み・方針だと対応難しそうです。

JavaScriptを使えば、URLとHTMLをsetIntervalで監視、該当すれば要素を非表示にするなどの実装で可能かと思います。
