### ISSUE TITLE
『詳細画面でもリプライ数、リツイート数、いいね数を隠す』を有効にすると、一部のページで文字が消えて読めなくなる

### ISSUE THREAD

**Issue by vojo915** [yusukesaitoh/calm-twitter#24]
# 概要

ログイン画面と予約ツイート管理画面で一部の文字が消えて読めません。

- 1.2.0まではこのような不具合は起きませんでした。
- 『Stylus』等のCSSにアクセスする拡張を無効にしても改善されません。
    -  『おだやかTwitter』以外の全ての拡張を無効にしても改善されません。
-  セキュリティソフトの広告ブロック機能は無効にしています。

## 環境

OS: Windows 10 21H2
ブラウザ: Google Chrome 100.0.4896.88

## 再現手順

1. 設定で『詳細画面でもリプライ数、リツイート数、いいね数を隠す』を有効にします。
1. 有効にした瞬間から一部のページで文字が消えて読めなくなります。
1. 無効にすれば再び文字が表示されて読めるようになります。

### ログイン画面

ボタンの文字が消えて読めません。

![login](https://user-images.githubusercontent.com/84438932/163218318-dfd5a522-95c6-454e-ae13-127024e62632.png)

### 予約ツイート管理画面

ボタン及び本文の文字が消えて読めません。

![yoyaku_tweet](https://user-images.githubusercontent.com/84438932/163218417-f619b9bc-143d-496c-bf67-6f6776ab2cf8.png)

**Comment by yusukesaitoh** [comment]
ご報告ありがとうございます。
『詳細画面でもリプライ数、リツイート数、いいね数を隠す』は結構強引にセレクタを書いており影響範囲見逃していました。
別のセレクタで実装できるか確認してみます（無いかもしれない）。

画面にhoverすれば文字が表示されることと、原因となる機能が個別にオフにできることを考慮して対応を考えたいと思います。

**Comment by pentamania** [comment]
突然のメッセージ失礼します。
カスタムCSSにて、以下の指定でも詳細画面のいいね数等を消すことができましたので報告させていただきます。

```css
span[data-testid="app-text-transition-container"] {
    display: none;
}
```

このセレクタでは本issueのような副作用は（自分が確認した限りでは）見られませんでした。
開発の参考になりましたら幸いです。

--- 

issueとは関係ありませんが、こちらの拡張のおかげで穏やかにtwitterできております。
素敵な拡張をありがとうございます🙏

**Comment by yusukesaitoh** [comment]
こちら Ver. 1.4.0 で修正したためCloseします。
https://github.com/yusukesaitoh/calm-twitter/pull/36
