### ISSUE TITLE
Hide the doge logo?

### ISSUE THREAD

**Issue by tomhannen** [yusukesaitoh/calm-twitter#43]
Is there any chance an update to the Calm plugin could remove the Doge dog logo that has replaced the twitter logo?
It is distracting.  Many thanks for a useful tool.

Google translate:
Calm プラグインの更新により、Twitter のロゴに取って代わった Doge のロゴが削除される可能性はありますか?
気を散らすものです。 便利なツールをありがとうございます。

**Comment by yusukesaitoh** [comment]
The Twitter bird is now back ：)
So this issue is resolved.
