### ISSUE TITLE
動画の再生回数を非表示にしたい

### ISSUE THREAD

**Issue by kmos2** [yusukesaitoh/calm-twitter#46]
すばらしい拡張を作ってくださり、ありがとうございます！
動画の再生回数を非表示にしたいのですが、可能でしょうか？
ご検討いただけると幸いです。
よろしくお願いいたします。

**Comment by kmos2** [comment]
間違えて３つ立ててしまいました。申し訳ありません。

**Comment by yusukesaitoh** [comment]
Web版Twitterで動画の再生回数を見つけられなかったのですが、どの画面のどの位置に表示されているか説明いただいても良いでしょうか？

**Comment by kmos2** [comment]
5月13日頃までは動画の左下に再生回数が表示されていたのですが、twitterの仕様変更で表示されなくなったと思われます。
お手数をおかけしてしまい申し訳ございませんでした。
