### ISSUE TITLE
Xのリンクが変更された影響で新リンクで拡張機能が動作しない

### ISSUE THREAD

**Issue by kyu08** [yusukesaitoh/calm-twitter#51]
素晴らしい拡張機能をありがとうございます！
いつも便利に使わせていただいています。

タイトルの通りですがリンク変更に伴って拡張機能が動作していないので報告させていただきます。
修正してみたらうまく動いたのでPRも送らせていただきます。

**Comment by JonahGrimm** [comment]
+1 I use this extension daily, and it makes browsing Twitter / X not overstimulating and a manageable experience. I also would like to see this issue resolved with the attached PR

**Comment by erikreeves** [comment]
Hello,

Apologies for lack of knowledge but how can I update my chrome extension manually ? Or when will this update be pushed to chrome store ?

Thanks so much for this I love this extension ❤️

**Comment by JonahGrimm** [comment]
> Hello,
> 
> Apologies for lack of knowledge but how can I update my chrome extension manually ? Or when will this update be pushed to chrome store ?
> 
> Thanks so much for this I love this extension ❤️

Just figured this out myself, it's pretty simple! 

1. Download repo from latest release.
2. Open repository in code editor of choice. (I used VSCode)
3. In the console, `npm install`. This gets the node modules
4. `npm run build` This generates a packaged zip.
5. Locate the generated .zip folder under `/packages/`, and extract its contents to a new folder.
6. In Chrome, go to `chrome://extensions`, with developer mode turned on, press the button on the upper left corner called "Load Unpacked." Select the folder.
7. You're done!

**Comment by eveil77** [comment]
Something that doesn't require a bunch of shady app downloads

**Comment by yusukesaitoh** [comment]
Thank you for all your comments and pull requests.

A merged version of #52 was uploaded to the store yesterday and is currently under review.
After it is released, I will submit a merged version of #53.

**Comment by yusukesaitoh** [comment]
With this fix, the Explore button in the left column and trends in the right column will be hidden, but the number of likes and retweets on tweets will still be displayed. I will also fix this issue in the next version.
#54

**Comment by erikreeves** [comment]
Thank you @yusukesaitoh ! ❤️
